autoDeploy: true
services:
  - type: web
    name: turso-db
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: BIND_ADDRESS
        value: "0.0.0.0:10000"
      - key: DATA_DIR
        value: "/data"
      - key: JWT_SECRET
        value: "KJCahIT4SIkilqH6MRSZ1jlQp2cVphBOaiaEGjk1JUA="
      - key: JWT_EXPIRY_HOURS
        value: "24"
      - key: ADMIN_USERNAME
        value: "admin"
      - key: ADMIN_PASSWORD
        value: "TJACuFbcLnBHN31Y"
      - key: RUST_LOG
        value: "turso_service=info"
      - key: SEED_USERS
        value: "das-creatives:nw2a.-QVN-85L||8"
    disk:
      mountPath: /data
      sizeGB: 1
